{% set name = "torchaudio" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pytorch/audio/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 82c2745a73172b495327ec36c6970ad5ad9d5d2ac44feeaea2617152f9393bf7
  patches:
    - 0001-support-ffmpeg-and-not-sox.patch
    - 0002-set-include-path.patch

build:
  number: 0
  env:
    - FFMPEG_ROOT=${PREFIX}
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - install_name_tool -add_rpath @loader_path/ $SP_DIR/torchaudio/lib/_torchaudio_ffmpeg6.so  # [osx]
    - install_name_tool -add_rpath @loader_path/ $SP_DIR/torchaudio/lib/_torchaudio_ffmpeg5.so  # [osx]
    - install_name_tool -add_rpath @loader_path/ $SP_DIR/torchaudio/lib/_torchaudio_ffmpeg4.so  # [osx]
    - install_name_tool -add_rpath @loader_path/ $SP_DIR/torchaudio/lib/_torchaudio.so  # [osx]
  ignore_run_exports:
    - pytorch-gpu
    - libprotobuf
  missing_dso_whitelist:
    - $RPATH/libc10.dylib
    # contained in ffmpeg
    - $RPATH/libavutil.*.dylib
    - $RPATH/libavcodec.*.dylib
    - $RPATH/libavformat.*.dylib
    - $RPATH/libavdevice.*.dylib
    - $RPATH/libavfilter.*.dylib
    # libsox shouldn't be activated to begin with
    - $RPATH/libsox.dylib
    # in pytorch package
    - $RPATH/libtorch.dylib
    - $RPATH/libtorch_cpu.dylib
    - $RPATH/libtorch_python.dylib
    # in protobuf package
    - $RPATH/libprotobuf.*.dylib


requirements:
  build:
    - cmake
    - make  # [not win]
    - patch     # [not win]
    - m2-patch  # [win]
    - protobuf
    - llvm-openmp  # [osx]
    - intel-openmp  # [not osx and blas_impl == 'mkl']
  host:
    - python
    - setuptools
    - wheel
    - pip
    - pytorch 2.1.0
    - pybind11
    - libabseil
  run:
    - python
    # according to compatibility matrix in
    # https://github.com/pytorch/audio/blob/v2.1.2/docs/source/installation.rst#compatibility-matrix
    - pytorch >=2.1.0,<2.2.0
    # according to optional dependencies
    # https://github.com/pytorch/audio/blob/v2.1.2/docs/source/installation.rst#optional-dependencies
    # in this special case we want users of channel sfe140ed to be able to use the load and save functions, therefore
    # at least ffmpeg (the mightiest of the backends) is specified as a run dependency.
    - ffmpeg >=4.4,<7
    - libprotobuf
  run_constrained:
    # according to optional dependencies
    # https://github.com/pytorch/audio/blob/main/docs/source/installation.rst#optional-dependencies
    # sox has been tested with version 14.4.2, but it is unlikely that other versions will work
    - sox >=14.4.2


{% set ignore_modules =                  " --ignore=test/torchaudio_unittest/backend/soundfile --ignore=test/torchaudio_unittest/backend/dispatcher/soundfile" %}
{% set ignore_modules = ignore_modules + " --ignore=test/torchaudio_unittest/backend/dispatcher/sox --ignore=test/torchaudio_unittest/backend/sox_io" %}

test:
  # source_files:
  #   - test/torchaudio_unittest
  imports:
    - torchaudio
  commands:
    - pip check
  #   - pytest -v {{ ignore_modules }} test/torchaudio_unittest
  # requires:
  #   - pip

about:
  home: https://pytorch.org/audio/stable/index.html
  summary: Torchaudio is a library for audio and signal processing with PyTorch.
  description: |
    The aim of torchaudio is to apply PyTorch to the audio domain. By supporting PyTorch, torchaudio follows the same
    philosophy of providing strong GPU acceleration, having a focus on trainable features through the autograd system,
    and having consistent style (tensor names and dimension names). Therefore, it is primarily a machine learning
    library and not a general signal processing library. The benefits of PyTorch can be seen in torchaudio through
    having all the computations be through PyTorch operations which makes it easy to use and feel like a natural
    extension.
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  doc_url: https://pytorch.org/audio/main/torchaudio.html
  dev_url: https://github.com/pytorch/audio

extra:
  recipe-maintainers:
    - boldorider4
